replicaCount:
  backend: 1
  frontend: 1

backend:
  image: ghcr.io/oegge/music-manager-backend
  tag: latest
  pullPolicy: IfNotPresent
  port: 8080
  mediaMountPath: /data/media
  extraEnv: { }
  LOG_LEVEL: info
  imagePullSecrets:
    - name: ghcr-cred
frontend:
  image: ghcr.io/oegge/music-manager-frontend
  tag: latest
  pullPolicy: IfNotPresent
  port: 80
  imagePullSecrets:
    - name: ghcr-cred
postgres:
  image: postgres
  tag: "16"
  port: 5432
  storage: 5Gi
  # You MUST change this before installing in real environments
  username: music
  database: musicdb
  password: "de2b1c29-684e-49f9-b3d0-b28b7f01fd08"

wwwroot:
  enabled: true
  storage: 100Gi
  # leave empty to use the cluster default StorageClass
  storageClassName: ""

media:
  storage: 50Gi
  storageClassName: "standard"

service:
  type: ClusterIP

ingress:
  frontend:
    enabled: true
    className: "nginx"
    host: music.above.de
    annotations: { }
    tls: [ ] # e.g. [{ secretName: music-frontend-tls, hosts: [music.local] }]
  backend:
    enabled: true
    className: "nginx"
    host: api.music.above.de
    annotations: { }
    tls: [ ]

resources:
  backend: { }
  frontend: { }
  postgres: { }

controller:
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  config:
    proxy-body-size: "50m"
  # make sure only one controller runs on a single-node dev cluster
  replicaCount: 1

  service:
    type: ClusterIP   # you don’t need NodePort/LoadBalancer anymore

  # If you had this on before (common with LB setups), turn it off
  publishService:
    enabled: false
