apiVersion: v1
kind: Service
metadata:
  name: {{ include "music-stack.fullname" . }}-postgres
  labels:
    {{- include "music-stack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: pg
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    app.kubernetes.io/name: {{ include "music-stack.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
