{{- if .Values.backup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "above.fullname" . }}-pg-table-backup
spec:
  schedule: {{ .Values.backup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: "postgres:{{ .Values.postgres.tag }}"
              imagePullPolicy: IfNotPresent
              env:
                - name: PGHOST
                  value: {{ printf "%s-postgres" (include "above.fullname" .) | quote }}
                - name: PGPORT
                  value: {{ .Values.postgres.port | quote }}
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "above.fullname" . }}-postgres-auth
                      key: database
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "above.fullname" . }}-postgres-auth
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ include "above.fullname" . }}-postgres-auth
                      key: password
              command: ["/bin/sh","-lc"]
              args:
                - |
                  set -euo pipefail
                  TS="$(date +%F_%H%M%S)"
                  TABLE="{{ .Values.backup.table }}"
                  OUT="/tmp/${TABLE//./_}_${TS}.dump"
                  pg_dump -F c -t "$TABLE" -f "$OUT" "$PGDATABASE"
                  gzip -9 "$OUT"
                  echo "Backup created: ${OUT}.gz"
{{- end }}
